@files = (
	['//project/propertySheet/property[propertyName="perlHeader"]/value', 'perlHeader.pl'],
	['//project/propertySheet/property[propertyName="ec_setup"]/value', 'ecSetup.pl'],
	['//project/procedure[procedureName="AddAllProjects"]/step[stepName="Iterate"]/command', 'commands/AddAllProjects_Iterate.pl'],
	['//project/procedure[procedureName="AddProject"]/step[stepName="Add"]/command', 'commands/AddProject_Add.pl'],
	['//project/procedure[procedureName="AddProject"]/step[stepName="Sanity"]/command', 'commands/AddProject_Sanity.pl'],
	['//project/procedure[procedureName="CommitAllProjectChanges"]/step[stepName="Iterate"]/command', 'commands/CommitAllProjectChanges_Iterate.pl'],
	['//project/procedure[procedureName="CommitProjectChanges"]/step[stepName="Commit"]/command', 'commands/CommitProjectChanges_Commit.pl'],
	['//project/procedure[procedureName="CommitProjectChanges"]/step[stepName="Sanity"]/command', 'commands/CommitProjectChanges_Sanity.pl'],
	['//project/procedure[procedureName="CreateProject"]/step[stepName="Create"]/command', 'commands/CreateProject_Create.pl'],
	['//project/procedure[procedureName="CreateProject"]/step[stepName="Sanity"]/command', 'commands/CreateProject_Sanity.pl'],
	['//project/procedure[procedureName="DeleteProject"]/step[stepName="Delete"]/command', 'commands/DeleteProject_Delete.pl'],
	['//project/procedure[procedureName="DiscardProjectChanges"]/step[stepName="Discard"]/command', 'commands/DiscardProjectChanges_Discard.pl'],
	['//project/procedure[procedureName="DiscardProjectChanges"]/step[stepName="Sanity"]/command', 'commands/DiscardProjectChanges_Sanity.pl'],
	['//project/procedure[procedureName="RemoveAllProjects"]/step[stepName="Iterate"]/command', 'commands/RemoveAllProjects_Iterate.pl'],
	['//project/procedure[procedureName="RemoveProject"]/step[stepName="Remove"]/command', 'commands/RemoveProject_Remove.pl'],
	['//project/procedure[procedureName="RollbackProjectChanges"]/step[stepName="Rollback"]/command', 'commands/RollbackProjectChanges_Rollback.pl'],
	['//project/procedure[procedureName="RollbackProjectChanges"]/step[stepName="Sanity"]/command', 'commands/RollbackProjectChanges_Sanity.pl'],
	['//project/procedure[procedureName="UpdateAllProjectStatuses"]/step[stepName="Cleanup"]/command', 'commands/UpdateAllProjectStatuses_Cleanup.pl'],
	['//project/procedure[procedureName="UpdateAllProjectStatuses"]/step[stepName="Iterate"]/command', 'commands/UpdateAllProjectStatuses_Iterate.pl'],
	['//project/procedure[procedureName="UpdateProjectStatus"]/step[stepName="Sanity"]/command', 'commands/UpdateProjectStatus_Sanity.pl'],
	['//project/procedure[procedureName="UpdateProjectStatus"]/step[stepName="Update"]/command', 'commands/UpdateProjectStatus_Update.pl'],
);
